version: "3.9"
services:
  redis:
    image: "redis"
    ports: 
    - "6379:6379"
  db:
    image: "postgres:11"
    ports:
    - "5432:5432"
    environment: 
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "user"
